/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Fabric({ children }: { children?: React.ReactNode }) {
  const { nodes } = useGLTF('/models/3_d_paths_lines_1.glb') as any
  return (
    <group scale={0.01}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Path_2.geometry}
        material={nodes.Path_2.material}
        position={[12.276, 219.697, -190.393]}
        rotation={[0.001, 0.025, -0.366]}
        scale={[0.652, 0.692, 0.557]}
      >
        {children}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Path_5.geometry}
        material={nodes.Path_5.material}
        position={[50.21, 267.75, 95.79]}
        rotation={[0, 0.025, -0.238]}
        scale={[0.493, 0.492, 0.419]}
      >
        {children}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Path_4.geometry}
        material={nodes.Path_4.material}
        position={[-221.269, 155.912, -346.674]}
        rotation={[0, 0.025, -0.224]}
        scale={[0.655, 0.653, 0.557]}
      >
        {children}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Path_3.geometry}
        material={nodes.Path_3.material}
        position={[228.037, 175.155, -28.181]}
        rotation={[0.001, 0.025, -0.344]}
        scale={[0.653, 0.629, 0.557]}
      >
        {children}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Path.geometry}
        material={nodes.Path.material}
        position={[70.272, 252.773, -45]}
        rotation={[0.001, 0.025, -0.366]}
        scale={[0.652, 0.63, 0.557]}
      >
        {children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/3_d_paths_lines_1.glb')
